export const routes = {
    dashboard: '/',
    branches: '/branches',
    positions: '/positions',
    employees: '/employees',
    employeeDetail: '/employees/:id',
    settings: '/settings',
    workShifts: '/work-shift',
    workSchedules: '/work-schedules',
    shiftRequests: '/shift-requests',
    leaveRequests: '/leave-requests',
    holidays: '/holidays',
    payrollPeriods: '/payroll-periods',
    salaryRules: '/salary-rules',
    rewardPenaltyCatalogs: '/reward-penalty-catalogs',
    attendance: '/attendance',
    payrollAdjustments: '/payroll-adjustments',
    payrollProcessings: '/payroll-processings',
    payslips: '/payslips',
} as const;
